### ISSUE TITLE
Odd comparability assistant window

### ISSUE THREAD

**Issue by CheesyFuck** [meetrevision/playbook#10]
I'm using a laptop
 Specs: 
Ryzen 5 5500u
Rtx3050
16gb ddr4 3200
512gb nvme ssd
ReviOS 23.05 (prerelesse)

During configuring at the cleaning up winsxs and removing appx this window pops up
![2023-05-07-15-37-13-658](https://user-images.githubusercontent.com/42902433/236664965-05c1e872-dcb0-403c-9770-5c20ed2b3353.jpg)

**Comment by CheesyFuck** [comment]
Im used a clean install of windows 11 22h2

**Comment by dreammjow** [comment]
I assume you haven't properly disabled Defender features, like Memory Integrity and Microsoft Vulnerable Driver Blocklist before applying the playbook.
