### ISSUE TITLE
[BUG]: Intel TSX significantly reduces performance on AMD CPU

### ISSUE THREAD

**Issue by PACHAKUTlQ** [meetrevision/playbook#100]
### Describe the bug

Revi playbook enables Intel TSX feature by default. In [Revision tool](https://github.com/meetrevision/revision-tool), it is described as:
> Add hardware transactional memory support, which helps speed up the execution of multithreaded software at the cost of security

However, enabling Intel TSX seems to significantly reduce performance on AMD CPU. For a simple C program that count prime numbers under 100000000, it takes `73` seconds to run with Intel TSX on, while `54` seconds with Intel TSX off. (Similar results when testing on Arch WSL using the same program)

### Steps to reproduce

1. Install Windows 11 on a laptop with AMD CPU
2. Run AME Wizard with Revi playbook, default configurations
3. Run a CPU performance testing program
4. Disable Intel TSX in `Performance` bar in Revision tool (auto-installed by the playbook)
5. Run the performance testing program again to find improved performance

### Expected behavior

Revi playbook can detect if running on AMD CPU, and disable Intel TSX automatically.

### Environment

- OS Build Number & Edition: `Windows 11 23H2 pro`
- ReviOS Version: `23.12`
- Specs: `CPU: AMD Ryzen 7840HS`

### Additional information

- As this bug is CPU-related, it may be hard to reproduce.
- Possible solutions:
    1. Make Intel TSX a Beta feature, disabled by default, and suggest Intel users to manually enable it in Revision tool
    2. Enable Intel TSX (as it is now), suggest AMD users to manually disable it in Revision tool
    3. If the bug can always be reproduced, let playbook detect CPU and auto manage the setting

### Have you searched for similar issues?

- [X] I have searched for similar issues and found none.

**Comment by Lyceris-chan** [comment]
add it to revert modifications as well to fix pre patched systems?
