### ISSUE TITLE
[BUG]: ReviOS playbook applied with errors

### ISSUE THREAD

**Issue by Givememynameplease** [meetrevision/playbook#101]
### Describe the bug

The installation of ReviOS in AME Wizard always ended up with "ReviOS playbook is applied with errors"
The logs are as follows:

[ErrorLog.txt](https://github.com/meetrevision/playbook/files/15276317/ErrorLog.txt)
[Packages.txt](https://github.com/meetrevision/playbook/files/15276318/Packages.txt)
[TIOutput.txt](https://github.com/meetrevision/playbook/files/15276319/TIOutput.txt)
[AdminOutput.txt](https://github.com/meetrevision/playbook/files/15276316/AdminOutput.txt)

### Steps to reproduce

1. Deploy ReviOS in AME Wizard

### Expected behavior

I expected ReviOS to be correctly applied.

### Environment

- OS Build Number & Edition: `Windows 10 22H2`
- ReviOS Version: `v23.12`
- Specs: `type here`

### Have you searched for similar issues?

- [X] I have searched for similar issues and found none.

**Comment by melo936** [comment]
Should be fixed by [Revision Tool 1.9.1 release](https://github.com/meetrevision/revision-tool/releases/tag/1.9.1).
