### ISSUE TITLE
[BUG]: ReviOS 23.12 install on latest version win10 got "SetupDiGetDeviceInterfaceDetail failed" while using GOSUN Qflash software

### ISSUE THREAD

**Issue by Valkierja** [meetrevision/playbook#108]
### Describe the bug

Im trying to flash a embeded device, but got this and crash
![image](https://github.com/meetrevision/playbook/assets/68413810/d714061a-672f-43df-8d5c-e49fbb341ad2)

my win10 version is 10.0.19045 
if any further info is needed, I will update ASAP

### Steps to reproduce

1. 
2. 
3. 
4. 

### Expected behavior

open  the software in clean win10 not cause any crash
so,  it might should not emit any crash while using it on revios23.12
(English is not my first language)

### Environment

- OS Build Number & Edition: `type here`
- ReviOS Version: `type here`
- Specs: `type here`

### Have you searched for similar issues?

- [X] I have searched for similar issues and found none.

**Comment by melo936** [comment]
I highly doubt that it's ReviOS related. If possible, please do a fresh install of one of the supported Windows builds and apply this playbook instead:

https://pixeldrain.com/u/MTnjkrWC

**Comment by Valkierja** [comment]
> I highly doubt that it's ReviOS related. If possible, please do a fresh install of one of the supported Windows builds and apply this playbook instead:
> 
> https://pixeldrain.com/u/MTnjkrWC

good point, I will try that

**Comment by Valkierja** [comment]
SOLVED
