### ISSUE TITLE
[BUG]: AME Wizard report v24.06 as malicious

### ISSUE THREAD

**Issue by AlreadyFree** [meetrevision/playbook#110]
### Describe the bug

AME Wizard report v24.06 as intentionally malicious and recommends deletion.

### Steps to reproduce

1. Add ReviOS Playbook v24.06 to AME Wizard
2. 
3. 
4. 

### Expected behavior

I expected the playbook to not be reported as intentionally malicious.

### Environment

- WIndows 10 LTSC 21H2

### Have you searched for similar issues?

- [X] I have searched for similar issues and found none.

**Comment by ChuonChuonBayThap** [comment]
It’s not an error, they always require time to verify the new version, like 1-3 days.
