### ISSUE TITLE
[BUG]: Applied With Errors?

### ISSUE THREAD

**Issue by berkkrkc09** [meetrevision/playbook#111]
### Describe the bug

I applied 24.06 on top of an existing ReviOS 23.12 Windows 11 but it applied with errors and told me to see the logs.

### Steps to reproduce

1. Run AME Wizard.
2. Run ReviOS 24.06 playbook.
3. follow the steps and choose options, apply.
4. Get error.

### Expected behavior

Apply without errors and restart the system into Windows.

### Environment

- OS Build Number & Edition: `11 Pro 23H2 22631.3593`
- ReviOS Version: `24.06`
- Specs: `AMD Ryzen 7 4800H, Nvidia GTX 1650 Ti Mobile, 24GB(1x8 + 1x16) 3200MHz DDR4 RAM`

### Additional information

This was the same with 23.12 on a clean install of Windows 11 but I didn't have the time to report it due to University. The device is a Lenovo IdeaPad gaming 3 laptop. The system is still usable after the errored installation if I restart it or start Explorer from Task Manager. Most Things applied but I think some switches do nothing in ReviTool because of the error including the [defender switch](https://imgur.com/a/7T9YEyh). Here are the logs for AME wizard: [AdminOutput.txt](https://gist.github.com/berkkrkc09/3b23bdf98faba38831cb581a405fbfbe), [Packages.txt](https://gist.github.com/berkkrkc09/d52d81745054f3babbe6901f3e0e2ab3), [ErrorLog.txt](https://gist.github.com/berkkrkc09/fa867b2a405235c2c571b00ff89fedd7), [TIOutput.txt](https://gist.github.com/berkkrkc09/27f6bfa6b3cc1d61bca1dd98e49a13a3). The defender error and logs are added as links from imgur and gist. I did search for similar issues and found some but they didn't get me anywhere. 
Edit: In pre-relase versions of ReviTool I saw errors about powershell when using some switches maybe it is about powershell?

### Have you searched for similar issues?

- [X] I have searched for similar issues and found none.

**Comment by melo936** [comment]
If I am not mistaken, AME Wizard may have issues on non-English language systems. Please change your system language to English (United States), download ReviOS Playbook and AME Wizard again just in case and apply the playbook again.

This is not related to ReviOS, therefore I'm closing it.

**Comment by berkkrkc09** [comment]
if I change it from English after applying it will it cause problems?

**Comment by berkkrkc09** [comment]
[AdminOutput.txt](https://github.com/user-attachments/files/15765484/AdminOutput.txt)
[ErrorLog.txt](https://github.com/user-attachments/files/15765485/ErrorLog.txt)
[Packages.txt](https://github.com/user-attachments/files/15765487/Packages.txt)
[TIOutput.txt](https://github.com/user-attachments/files/15765488/TIOutput.txt)
still getting errors after switching to English as system language

**Comment by berkkrkc09** [comment]
I have another machine that applies the same playbook file with the same AME Wizard.exe + Turkish set as system language. This does not happen to it. I need more help about this.
