### ISSUE TITLE
[BUG]: cant install AMD Radon　Software

### ISSUE THREAD

**Issue by Tartarusome** [meetrevision/playbook#113]
### Describe the bug

![image](https://github.com/meetrevision/playbook/assets/142856268/101bae6f-d717-4c1e-b1b4-984040a69b22)

### Steps to reproduce

the msix of this app have more details

应用安装失败，错误消息: Windows 无法安装程序包 AdvancedMicroDevicesInc-2.AMDRadeonSoftware_10.22.40027.0_x64__0a9344xs7nr4m，因为找不到此程序包依赖的设备驱动程序。必须安装以下设备驱动程序之一: {[Advanced_Micro_Devices,_Inc.-UWPPair.inf, 31.2240.0.0]} (0x80073cfd)

### Expected behavior

1

### Environment

win11, playbook, all is latest

### Have you searched for similar issues?

- [X] I have searched for similar issues and found none.

**Comment by ChuonChuonBayThap** [comment]
In most case, it's a Windows's problem (drivers install from Windows Update, Microsoft Store are sucks), i faced this problem too. Use DDU to fully remove your AMD driver, then download it from offical AMD website.

**Comment by PACHAKUTlQ** [comment]
It is likely a Windows's problem. Can you install this using the original MS Store?

**Comment by NextWork123** [comment]
> ### Describe the bug
> 
> ![image](https://private-user-images.githubusercontent.com/142856268/338513106-101bae6f-d717-4c1e-b1b4-984040a69b22.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0MzY5MDAsIm5iZiI6MTczMzQzNjYwMCwicGF0aCI6Ii8xNDI4NTYyNjgvMzM4NTEzMTA2LTEwMWJhZTZmLWQ3MTctNGMxZS1iMWI0LTk4NDA0MGE2OWIyMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNVQyMjEwMDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZDEzOTc3YTNmYmE5N2Y0YzA0NDg1MDJhZTY2MDNhZjZhZDY1ZmU3YjgyZDY5YTAwZmI3MTEyY2YxODBjMWJiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.qOmPAk2abXv-aozcmXHSiMTu7IsHGg6uimLSV73CUqg)
> ### Steps to reproduce
> 
> the msix of this app have more details
> 
> 应用安装失败，错误消息: Windows 无法安装程序包 AdvancedMicroDevicesInc-2.AMDRadeonSoftware_10.22.40027.0_x64__0a9344xs7nr4m，因为找不到此程序包依赖的设备驱动程序。必须安装以下设备驱动程序之一: {[Advanced_Micro_Devices,_Inc.-UWPPair.inf, 31.2240.0.0]} (0x80073cfd)
> ### Expected behavior
> 
> 1
> ### Environment
> 
> win11, playbook, all is latest
> ### Additional information
> 
> _No response_
> ### Have you searched for similar issues?
> 
>     * [x]  I have searched for similar issues and found none.

you need specific components for use the app, go with the official one isn't so much different.
