### ISSUE TITLE
[BUG]:  If there is no operation for 1 minute, the screen will automatically be locked and the setting will be invalid.

### ISSUE THREAD

**Issue by guoxiao0521** [meetrevision/playbook#118]
### Describe the bug

After 1 minute of inactivity, the system will automatically enter the lock screen and ask me to enter the mask number.

### Steps to reproduce

1. Wait 1 minute
2. 
3. 
4. 

### Expected behavior

Don't always jump to the lock screen

### Environment

- OS Build Number & Edition: `win11 23h2`
- ReviOS Version: `June 9, 2024`

### Have you searched for similar issues?

- [X] I have searched for similar issues and found none.

**Comment by melo936** [comment]
During applying the playbook or? Your issue isn't clear

**Comment by guoxiao0521** [comment]
I'm sorry, it's my problem. It's been solved.
issue close

**Comment by guoxiao0521** [comment]
I'm sorry, it's my problem. It's been solved.
issue close
