### ISSUE TITLE
[BUG]: Windows Update can't update driver on build 26100.1150

### ISSUE THREAD

**Issue by DRCRecoveryData** [meetrevision/playbook#121]
### Describe the bug

I have enable update drivers thought Windows Update but drivers can't update

Also copilot shortcut still on taskbar

### Steps to reproduce

1. Please check drivers disable option
2. Please check copilot remove option

### Expected behavior

I think drivers update disable wrong on new windows build

### Environment

- OS Build Number & Edition: `26100.1150`
- ReviOS Version: `Revi-PB-24.06`
- Specs: `HP-Pavillion-15S`

### Have you searched for similar issues?

- [X] I have searched for similar issues and found none.

**Comment by melo936** [comment]
Open PowerShell as administrator and enter the following command:

```powershell
& "C:\Program Files (x86)\Revision Tool\revitool.exe" winpackage --install system-components-removal
```

**Comment by DRCRecoveryData** [comment]
> Open PowerShell as administrator and enter the following command:
> 
> 
> 
> ```powershell
> 
> & "C:\Program Files (x86)\Revision Tool\revitool.exe" winpackage --install system-components-removal
> 
> ```

Hi,

Have you check the copilot shortcut issue?
