### ISSUE TITLE
[BUG]: Keyboard/Trackpad stops working after waking up Laptop from sleep mode.

### ISSUE THREAD

**Issue by Louis047** [meetrevision/playbook#124]
### Describe the bug

I usually keep my laptop turned on for using it as a hotspot for my phone overnight and the next day I wake up and check on it only to see that the neither the keys in the keyboard nor the trackpad works and had to get my mouse every time for navigation.

### Steps to reproduce

A common issue for Laptop users

### Expected behavior

Keyboard/Track pad working normal

### Environment

- OS Build Number & Edition: `26100.1 Windows 11 IoT LTSC`
- ReviOS Version: `24.06`
- Specs: `ASUS TUF A15 2021: AMD Ryzen 7 5800H 3.2GHz, 16GB SODIMM 3200MHz, RTX 3060 6GB GDDR6`

### Additional information

I changed the power plan back to optimized default `Balanced` as I use a software called G-Helper and my laptop also supports multiple modes `Eco Balanced Turbo` which prefers the default power plan.

I would like to address a common issue with laptops here:
Every time when one try to implement/add a new power plan (eg: Adding Ultimate Performance power plan to laptop) it applies for that session and after a reboot, it disappears like it was not even applied in the first place, thereby leading to persistent issue.

I have tried to keep the laptop awake by changing the sleep time. Works but laptop gets locked automatically.

### Have you searched for similar issues?

- [X] I have searched for similar issues and found none.

**Comment by melo936** [comment]
Does this also happen on a fresh install of 26100? It may not be related to ReviOS at all.

**Comment by Louis047** [comment]
I didn't face the issue in stock windows iirc.

I suppose the changes made in the sleep mode might have contributed to the issue.

Now that I moved back to `Windows 11 23H2 Build: 26631.3880` it might take time for me to test things since I'm currently busy with exams.

**Comment by Louis047** [comment]
Update:

Seems like the issue has been solved in 23H2, maybe because 24H2 isn't ready yet.
