### ISSUE TITLE
[FEATURE REQUEST] Disable WPBT and Bitlocker automatic encryption

### ISSUE THREAD

**Issue by wevsty** [meetrevision/playbook#13]
About WPBT:
What is WPBT?
Suggested Reference https://github.com/Jamesits/dropWPBT

The disabling method is also very simple, just add the following registry values
```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager]
"DisableWpbtExecution"=dword:00000001
```

About bitlocker automatic encryption:
Windows will automatically enable Bitlocker for all disks after some conditions are met.
I recommend adding the following registry entry to prevent Bitlocker from automatically encrypting the disk.
```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\BitLocker]
"PreventDeviceEncryption"=dword:00000001
```
Microsoft's description link reference:
https://learn.microsoft.com/en-us/windows/security/information-protection/bitlocker/bitlocker-device-encryption-overview-windows-10#bitlocker-device-encryption

**Comment by dreammjow** [comment]
Done.
