### ISSUE TITLE
[BUG]: 'Revision-Ultra performance' power plan will disappear

### ISSUE THREAD

**Issue by Dillensad** [meetrevision/playbook#132]
### Describe the bug

When I switch the power plan to 'balance' in the control panel, the original 'Revision-Ultra performance' will disappear forever, and then I cannot switch back to it

### Steps to reproduce

1. find the power plan in the control panel and turn on the 'balance' power plan instead of 'Revision'
2. 
3. 
4. 

### Expected behavior

I hope this could be fixed 

### Environment

- OS Build Number & Edition: 23H2 22631.3880
- ReviOS Version: 24.06
- Specs: lenovo XiaoXinPro 16 IMH9 
- CPU Intel(R) Core(TM) Ultra 9 185H   2.30 GHz

### Have you searched for similar issues?

- [X] I have searched for similar issues and found none.

**Comment by melo936** [comment]
Do you have a Lenovo software installed?

**Comment by Dillensad** [comment]
> Do you have a Lenovo software installed?

yes, I have the [Lenovo Vantage] on my laptop, is it the cause?

**Comment by melo936** [comment]
Yes, it is
