### ISSUE TITLE
[FEATURE]: Can an offline version be made? In the area where I am, I cannot connect to the server to download files and cannot deploy.

### ISSUE THREAD

**Issue by aoy2024** [meetrevision/playbook#137]
### Description

Can an offline version be made? In the area where I am, I cannot connect to the server to download files and cannot deploy.

### Benefit

Can an offline version be made? In the area where I am, I cannot connect to the server to download files and cannot deploy.

### Have you searched for similar feature requests?

- [X] I have searched for similar feature requests and found none.

**Comment by melo936** [comment]
Duplicate of #72
