### ISSUE TITLE
Hash of Playbook and Revision Tool

### ISSUE THREAD

**Issue by brwlsnf** [meetrevision/playbook#14]
Greetings. 

When downloading ReviOS Playbook and Revision Tool, from their Github pages, I can't find hashes of these two to verify them after downloading. 

Looked for any info in the FAQ, searched in Support Forums and found nothing. Am I only one who is too paranoiac about verifying downloaded files from the internet, I'm not sure but from my search in the forums it seems like...  

Anyway, so will it be polite if I say that I would like to kindly request the hashes of these files, for example, to be put/showed in the download pages' descriptions of those files in GitHub?

Thanks in advance and in anyway.

**Comment by brwlsnf** [comment]
That's the answer I've got in the Support Forum of Revision Discord.
![23B7CABA-2F63-4937-9D36-F9044A956E02](https://github.com/meetrevision/playbook/assets/135496644/c6846680-f4a1-4191-a9ea-7181476003ea)

**Comment by brwlsnf** [comment]
> does the github api expose the files' checksums in releases?

I don't get what you want to say in your question, that is addressed to my question as an answer.

**Comment by dreammjow** [comment]
AME Wizard automatically checks for hashes, but sure we will provide it next time.

**Comment by brwlsnf** [comment]
> AME Wizard automatically checks for hashes, but sure we will provide it next time.

Thank you. Wish you have a nice day
