### ISSUE TITLE
[FEATURE]: Can we have a build with muted Windows Edition Check for testing?

### ISSUE THREAD

**Issue by devizer** [meetrevision/playbook#141]
### Description

Can we have a revi build with muted Windows Edition Check for testing?

For example, A warning instead of blocking installation "Warning. This Windows build was not tested"

It is as dangerous as installing on existing Windows Installation. 

### Benefit

We will be able to test on new versions of Windows and Windows Server.

Software developers need to test soft on supported CPUs with a small amount of RAM, such as Intel Atom and Intel Celeron.
So debloating new insider versions and windows server is essential for us and software quality. 

### Implementation (Optional)

As mentioned in the description a warning should replace existing installation blocker "Warning. This Windows build was not tested"

### Have you searched for similar feature requests?

- [X] I have searched for similar feature requests and found none.

**Comment by Pyenb** [comment]
You can basically do that yourself. Open the [playbook.conf](https://github.com/meetrevision/playbook/blob/main/src/playbook.conf) and remove the `SupportedBuilds` check. Then you'll be able to install it on every version.

To pack it back into a playbook just take everything from inside the `src` folder, compress it to a .zip file and rename the extension to .apbx. See [here](https://docs.ameliorated.io/developers/getting-started/creation.html) for more information.
