### ISSUE TITLE
Arm Support

### ISSUE THREAD

**Issue by boskiv** [meetrevision/playbook#19]
Is it possible to add ARM build to the pipeline?

**Comment by dreammjow** [comment]
The playbook should work for ARM, but Revision Tool will not work at the moment.

**Comment by melo936** [comment]
Due to recent changes in 23.12, removing system packages isn't available for ARM.

**Comment by n00b69** [comment]
ReviOS works fine on ARM, except for the fact that it installs x64 versions of browsers.

**Comment by n00b69** [comment]
> I see the new entry [in the changelog](https://github.com/meetrevision/playbook/releases/tag/24.06) "Initial ARM64 support (Thanks to @n00b69)". Can this be further explained so we can understand how/why this is "initial" and perhaps tentative sounding vs more concrete?
> 
> Are there still more issues to work through to get such support solidified and to par with standard releases?

I'll try to install it one of these days to see if I can find any issues. Currently using AtlasOS due to the previous lack of ARM64 support (after my last post I figured out that it didn't debloat Windows so well after all at the time)

**Comment by melo936** [comment]
ReviOS Playbook 24.06 only works on Windows 11 ARM64 systems, because of [Arm64EC](https://learn.microsoft.com/en-us/windows/arm/arm64ec). Why? Revision Tool currently doesn't provide arm64 builds at the moment.

**Comment by n00b69** [comment]
It had one a few months ago, it's fully working

**Comment by n00b69** [comment]
> > It had one a few months ago, it's fully working
> 
> I'm using lumia 950xl with win10 can I use revios on win10 arm? if no, what do you think is better for my device, win11+revios or a standard debloated win10 pro?

ARMv7? Latest Windows 11 does not work on it.
