### ISSUE TITLE
Unable to sign in to xbox

### ISSUE THREAD

**Issue by andcortez** [meetrevision/playbook#2]
Hello, I fresh install windows 11 original ISO from microsoft website, and used the playbook with AME Wizard, and i'm trying to use xbox services (game bar and xbox app) but i cannot sign. Anyone help me?

**Comment by dreammjow** [comment]
@andcortez

Open Terminal as administrator and run the commands below:

```
reg delete "HKLM\SYSTEM\ControlSet001\Services\SharedAccess\Defaults\FirewallPolicy\FirewallRules" /v "Block-Windows-Insider" /f
reg delete "HKLM\SYSTEM\ControlSet001\Services\SharedAccess\Parameters\FirewallPolicy\FirewallRules" /v "Block-Windows-Insider" /f
```
