### ISSUE TITLE
Can I upgrade my system from win10 to win11 using your Playbook?

### ISSUE THREAD

**Issue by petercao** [meetrevision/playbook#20]
Can I upgrade my system from win10 to win11 using your Playbook?
and how to do?
I can only see your upgrade image .apbx from blew link:
[Revi-PB-23.07.apbx](https://github.com/meetrevision/playbook/releases/download/23.07/Revi-PB-23.07.apbx)

**Comment by dreammjow** [comment]
The upgrade process is unrelated to Playbooks. You can use Installation Assistant or Create Windows Installation Media to upgrade to 11 and then apply the playbook.
