### ISSUE TITLE
Revios Playbook applied over Revios ISO instalation

### ISSUE THREAD

**Issue by BrutolocoW** [meetrevision/playbook#25]
It turns out that I applied the playbook in a Revios installation, I did it because I had accidentally applied the windows updates, and Edge appeared and who knows what else. It occurred to me that there might be a way to fix it.

Apparently it doesn't seem like I have any problems, I would like to know if this could be problematic. I think a lot of people could ask themselves the same question if they find themselves in a similar situation.

**Comment by melo936** [comment]
Hi,

On our server, there were similar reports a couple of days ago without even enabling updates. I assume something is wrong with the "Configure Automatic Updates" policy or some other components which rely on WU triggers it. We disable the policy, but looks like it doesn't work. In the last two commits - fe5d70c & ce05edb (fixes the wrong value) - we will mitigate it by pausing updates until 2038 and the toggle for it in Revision Tool will be provided.

**Comment by BrutolocoW** [comment]
> Hola,
> 
> En nuestro servidor, hubo informes similares hace un par de días sin siquiera habilitar las actualizaciones. Supongo que algo está mal con la política "Configurar actualizaciones automáticas" o algunos otros componentes que dependen de que WU lo active. Deshabilitamos la política, pero parece que no funciona. En las últimas dos confirmaciones, [ fe5d70c ](https://github.com/meetrevision/playbook/commit/fe5d70c0a349700be2594ea18279590e3b33edb3) y [ ce05edb ](https://github.com/meetrevision/playbook/commit/ce05edb60d4ef38b6cc0230b003762832cad1d34) (corrige el valor incorrecto), lo mitigaremos pausando las actualizaciones hasta 2038 y se proporcionará la alternancia en la herramienta de revisión.

I didin't know that, in my case, I did the update by myself, finally I installed it all again. But still I have this question, what happens if revios playbook is applied over revios iso installation.

**Comment by baechooYT** [comment]
> > Hola,
> > En nuestro servidor, hubo informes similares hace un par de días sin siquiera habilitar las actualizaciones. Supongo que algo está mal con la política "Configurar actualizaciones automáticas" o algunos otros componentes que dependen de que WU lo active. Deshabilitamos la política, pero parece que no funciona. En las últimas dos confirmaciones, [ fe5d70c ](https://github.com/meetrevision/playbook/commit/fe5d70c0a349700be2594ea18279590e3b33edb3) y [ ce05edb ](https://github.com/meetrevision/playbook/commit/ce05edb60d4ef38b6cc0230b003762832cad1d34) (corrige el valor incorrecto), lo mitigaremos pausando las actualizaciones hasta 2038 y se proporcionará la alternancia en la herramienta de revisión.
> 
> I didin't know that, in my case, I did the update by myself, finally I installed it all again. But still I have this question, what happens if revios playbook is applied over revios iso installation.

It will do almost nothing.
because ReviOS Playbook is created by using [NTLite Migration Tool](https://docs.ameliorated.io/developers/ntlite.html)
It's just ReviOS ISO version imported to AME Wizard.
