### ISSUE TITLE
EDGE removal option

### ISSUE THREAD

**Issue by mikinko** [meetrevision/playbook#26]
is it possible to give option to not remove edge ? /in browser selection for example / ? thank you

**Comment by baechooYT** [comment]
well, revision probably not going to add removal option because of performance dropping issues.
but if you still want to install Microsoft edge you can install at: [Microsoft Edge Download](https://www.microsoft.com/edge/download)

**Comment by melo936** [comment]
> is it possible to give option to not remove edge ? /in browser selection for example / ? thank you

It is planned, and it will be available in the 23.09 release.
