### ISSUE TITLE
`msedgewebview2.exe` seems unable to send websocket data

### ISSUE THREAD

**Issue by ImUrX** [meetrevision/playbook#27]
We have an app that is based on webview, and the websocket packets come through the `msedgewebview2.exe` binary instead of the app itself.
For some reason the client receives packets and ACKs them but they can't send packets, like something is not letting it send Websocket packets specifically, the connection does require a HTTP GET from the client which does happen.

The app I'm talking about is [SlimeVR](https://github.com/SlimeVR/SlimeVR-Server)

**Comment by ImUrX** [comment]
This happens always on a ReviOS installation, that's why I'm making this issue

**Comment by melo936** [comment]
I can reproduce it as well on Windows 11.

> netsh int tcp set supplemental internet congestionprovider=default

This seems to have fixed the issue for me. Please report it back.

**Comment by ButterscotchV** [comment]
> I can reproduce it as well on Windows 11.
> 
> > netsh int tcp set supplemental internet congestionprovider=default
> 
> This seems to have fixed the issue for me. Please report it back.

Can confirm this works to fix the problem, thank you.
