### ISSUE TITLE
Browser suggestion

### ISSUE THREAD

**Issue by Edgars-Cirulis** [meetrevision/playbook#28]
I'm sure you all want a user-friendly playbook that doesn't force software like Microsoft does with Edge. Please add an option to not force install any browsers like Brave, Mozilla, etc. I mainly want to use Chrome or any other. Why would I need other browsers?

**Comment by melo936** [comment]
The [None](https://docs.ameliorated.io/developers/features/pages/radioimagepage.html#none-property) property has been available since 23.09
