### ISSUE TITLE
Windows 10 lighter

### ISSUE THREAD

**Issue by ulises2k** [meetrevision/playbook#29]
Is there a possibility of eliminating Xbox and everything related to gaming?
Leave Windows with the minimum to use it, for example, as a Trading Terminal, nothing more.

**Comment by ulises2k** [comment]
Check this:
https://github.com/LeDragoX/Win-Debloat-Tools

**Comment by melo936** [comment]
We're thinking about adding another [CheckboxPage](https://docs.ameliorated.io/developers/features/pages/checkboxpage.html) that allows you to remove Xbox, Your Phone, and a few other UWP apps, but it's important to ensure that removing them won't cause any issues. We ran into a problem in the past when we removed Your Phone and had trouble getting it to work properly after reinstalling.

**Comment by ulises2k** [comment]
Cortana and OneDrive too
