### ISSUE TITLE
How to enable Copilot in 23.09?

### ISSUE THREAD

**Issue by lukaschan** [meetrevision/playbook#32]
Updated to latest 23.09, but can't see Copilot in taskbar and taskbar settings.

So how to enable?

Must Edge be installed first?

THANKS.

**Comment by melo936** [comment]
Copilot relies on Edge (not even on EdgeWebView, shame!!), so yeah, it must be installed.

This may help in case Copilot doesn't show up:
`microsoft-edge:///?ux=copilot&tcp=1&source=taskbar`
