### ISSUE TITLE
BUG: Microsoft Edge has not been removed

### ISSUE THREAD

**Issue by A7exSchin** [meetrevision/playbook#33]
I followed the new playbook instructions and selected Firefox as browser instead of Brave. However, the Microsoft Edge browser has not been removed from my system. How can I remove it?

**Comment by melo936** [comment]
Please read the warning section, [here](https://github.com/meetrevision/playbook/releases/tag/23.09), and reapply the playbook.

Unfortunately, nothing our team can do.

**Comment by A7exSchin** [comment]
That is interesting. I am currently reapplying the Playbook. Selected Firefox again, but I do not have any additional page with checkboxes? Pressing next just starts the process of applying the playbook. I do not get an option to choose to keep or uninstall Edge, like it says in your latest patchnotes...

**Comment by A7exSchin** [comment]
Reapplying the playbook, with the option chosen to remove Edge, does in fact, not remove Edge...

**Comment by melo936** [comment]
> Reapplying the playbook, with the option chosen to remove Edge, does in fact, not remove Edge...

It should, unless Edge is installed for the current user.

**Comment by MrGrymReaper** [comment]
One of the traces it leaves behind is the pinned section, where the icon for Microsoft Edge once was. The user has to unpin the icon each time they do a new setup on a fresh install. Maybe the playbook could include as part of the process, unpinning the entry for Edge from the taskbar.

**Comment by melo936** [comment]
> One of the traces it leaves behind is the pinned section, where the icon for Microsoft Edge once was. The user has to unpin the icon each time they do a new setup on a fresh install. Maybe the playbook could include as part of the process, unpinning the entry for Edge from the taskbar.

The official method of uninstalling Edge already takes care of the unpinning process from the taskbar, as shown here: https://github.com/meetrevision/playbook/blob/832abcfec92949088465c78941a1c73606f28813/src/Executables/EDGE.cmd#L7-L14

Additionally, we have an alternative method in case the previous one doesn't work perfectly, which can be found here: https://github.com/meetrevision/playbook/blob/832abcfec92949088465c78941a1c73606f28813/src/Executables/EDGE.cmd#L7-L14

Assuming that the taskbar cache doesn't get cleared properly, although I couldn't reproduce the issue during testing a couple of times, it still perfectly unpins Edge after uninstallation.

For further investigation, please provide details on what you selected in Custom Features, details about your Windows build, and any other steps to reproduce the issue. This information will help us find and fix the issue.

**Comment by A7exSchin** [comment]
So this was my first time using the AME Wizard so basically I did the following:


1. Create a fresh ISO using the Windows Media Creation tool, for my current OS (Win 11 Pro)
2. Delete Partitions and install the fresh windows (22H2, build 22621.2428).
3. Let the Windows Update whatever it wants, until it does not find updates anymore
4. Install updated drivers, like NVidia GPU and Intel Thunderbolt Drivers from the Laptops Manufacturer
5. Run the AME Wizard, selecting the latest ReviOS Playbook
6. On Browser Setup Click Firefox
7. On pressing the OK button it started installing

Then i realized that Edge was not removed, so I asked here. people told me to rerun the playbook.
Thats what I did:
1. Start AME Wizard
2. Rerun Playbook
3. On Browser selection select "None", which only then lets me choose custom options.
4. "Remove Edge" was checked
5. Ran the Playbook
6. Edge wasnt removed

I hope that helps somehow

**Comment by preston176** [comment]
I think you can use third-party Uninstaller like [IOBit Uninstaller](https://www.iobit.com/en/advanceduninstaller.php) which even removes registry & traces of the file

I used to remove bloatware manually the likes of (OneDrive, Outlook, Edge) on Stock Win 10 & 11
