### ISSUE TITLE
I tried using Playbook on Windows 11 Pro For Workstations and it didn't work.

### ISSUE THREAD

**Issue by ImMejor35** [meetrevision/playbook#35]
It was permanently stuck on reticulating splines waited 3 hours with but nothing happened.

**Comment by melo936** [comment]
Please double-check whether Realtime Protection, Tamper Protection, Memory Integrity, and Vulnerable Driver Blocklist are disabled in Windows Defender are disabled in Windows Defender, and then reapply the playbook.

**Comment by ImMejor35** [comment]
I have decided to simply not use the playbook thank you for your comment.
