### ISSUE TITLE
[BUG] Removing Windows Backup!

### ISSUE THREAD

**Issue by 6xatz** [meetrevision/playbook#38]
Version: Windows 11 (23H2) 22631.2361.

After using the latest AME wizard with ReviOS Playbook 23.10 Pre Release 5.
Somehow, User Account Control settings unable to open (still presence in God Mode and Starallback but gone in control panel ).
Now I switch to UAC from registry.

![image](https://github.com/meetrevision/playbook/assets/58832421/cc3aa27f-c20d-4f4c-b009-a9928a6b3b55)

**Comment by preston176** [comment]
But is it functional?

**Comment by melo936** [comment]
I cannot reproduce it on 22631.2506
