### ISSUE TITLE
Revi os open source?

### ISSUE THREAD

**Issue by baaannnaaannn** [meetrevision/playbook#4]
Is revi os open source after relising playbook on GitHub?

**Comment by dreammjow** [comment]
Yes, it is now open-source.

**Comment by baaannnaaannn** [comment]
> Yes, it is now open-source.

And can I update revi os with this playbook? Or need install upgrade iso?

**Comment by dreammjow** [comment]
No, you need the latest upgrade ISO. FYI, Playbooks are highly recommended to be used on normal Windows, preferable fresh install.
