### ISSUE TITLE
DevHome getting deleted

### ISSUE THREAD

**Issue by castrosu** [meetrevision/playbook#41]
I installed Windows 23H2+ just to have DevHome and it worked but after applying the new Revision Playbook 23.10 it deleted the DevHome even the the option turned on meaning to install or keep DevHome installed.

**Comment by melo936** [comment]
Sorry for the confusion, it meant to remove DevHome.

It will be fixed soon.

**Comment by castrosu** [comment]
Oh yeah makes sense no worries

**Comment by castrosu** [comment]
Its written correctly, just be being stupid and not being able to read, my bad…
