### ISSUE TITLE
[FEATURE] More options for microsoft store apps

### ISSUE THREAD

**Issue by SirDank** [meetrevision/playbook#44]
Allow disabling uninstall of certain Microsoft Store apps such as:
- Windows Media Player
- Microsoft Photos
- Paint 3D

Just as there are options to disable the installation of Brave, etc.

**Comment by irkella** [comment]
> Allow disabling uninstall of certain Microsoft Store apps such as:
> 
> * Windows Media Player
> * Microsoft Photos
> * Paint 3D
> 
> Just as there are options to disable the installation of Brave, etc.

I do personally reinstall Microsoft Photos using the .msixbundle, not sure if that's possible for the other apps

**Comment by melo936** [comment]
Providing options for each UWP package that we remove could make the 'Custom Features' page difficult to navigate. Packages that can be easily reinstalled from the MS Store or Revision Tool should not be included there unless they are causing problems or decided by the team.

**Comment by SirDank** [comment]
@melo936 fair point, maybe it could be categorized as 'UWP Packages' and all apps would be listed under it?

**Comment by melo936** [comment]
As far as I am aware, AME Wizard allows you to add only four items per page
