### ISSUE TITLE
[BUG]: Can't rerun playbook after 23H2 upgrade

### ISSUE THREAD

**Issue by Talmidi** [meetrevision/playbook#46]
### Describe the bug

Per revi's recommendations I installed a stock windows iso from MSFT website.   I upgraded to 23H2. Then I ran AME/Revi playbook first time (success).  Today I checked task manager and found unexpected antimwalware executables that were running after the initial playbook run.  I attempted to rerun playbook and AME is stuck in loop "Checking Windows Security" and shadow defender processes interfere with second playbook run.

![2023-11-11_09-47](https://github.com/meetrevision/playbook/assets/111231372/9a5751e6-f8d5-4764-819e-26616966b7e0)

### Steps to reproduce

1. Clean install windows from stock MSFT Windows 64bit 11 iso
2. After initial install upgrade to 'optional windows features' (copilot preview build) 23H2
3. Install AME + REVI playbook
4. Attempt to rerun REVI playbook a second time after a week from the first run
5. Click on "Disable Windows Security"
6. AME Wizard stuck on checking windows security, but windows securtiy menu disabled after initial run

### Expected behavior

I expected to be able to rerun playbook after a first successful initial run.  

### Environment

- OS Build Number & Edition: `Windows 11 Pro N 23H2`
- ReviOS Version: `Revi-PB-23.10`
- Specs: 
Edition	Windows 11 Pro N
Version	23H2
Installed on	‎11/‎5/‎2023
OS build	22631.2506
Experience	Windows Feature Experience Pack 1000.22677.1000.0

### Additional information

[process_list.csv](https://github.com/meetrevision/playbook/files/13325020/process_list.csv)

### Have you searched for similar issues?

- [X] I have searched for similar issues and found none.

**Comment by melo936** [comment]
https://www.revi.cc/docs/faq/after/defender
