### ISSUE TITLE
[BUG]: UWP Applications can't be installed.

### ISSUE THREAD

**Issue by cub-has-injected** [meetrevision/playbook#47]
### Describe the bug

I tried to install the UWP app, which got uninstalled by Playbook, but it gave an error about my windows not installing packages made for "Windows.Xbox" or other errors.

![image](https://github.com/meetrevision/playbook/assets/83903792/61a96a3e-9cdd-46b2-8017-071afc85c3e6)
![image](https://github.com/meetrevision/playbook/assets/83903792/c2d79846-3d2f-4981-b54f-9ee85c2a0d19)

### Steps to reproduce

1. Install ReviOS in Playbook
2. Try to install any UWP app from the Microsoft Store or Revision Tool.

### Expected behavior

The app should install without any errors, with an output like this:
![image](https://github.com/meetrevision/playbook/assets/83903792/d3d894d6-9c2f-4afc-9c4a-7e066d6cb9f1)

### Environment

- OS Build Number & Edition: `22H2: 22621.2715, Home Single Language`
- ReviOS Version: `23.10`
- Specs: `Intel Core i3-7020U, NVIDIA MX110, 20GB RAM, HDD`

### Additional information

After installation, explorer has crashed once with the error "Hard error".

### Have you searched for similar issues?

- [X] I have searched for similar issues and found none.

**Comment by melo936** [comment]
The issue seems to be related to Revision Tool rather than the playbook. Installing Photos from MS Store works without any problems.

Based on the provided screenshots, I assume that the reason it doesn't install from Revision Tool is that `eappxbundle` gets downloaded instead of `.appxbundle`.

**Comment by cub-has-injected** [comment]
Windows has already fixed the problem somehow. Thanks for the help.

**Comment by melo936** [comment]
The issue in Revision Tool was fixed in 1.6.2
