### ISSUE TITLE
[FEATURE REQUEST] - Use NTSuspendProcess and/or Image File Execution Options to disable processes and services instead of permanently removing them

### ISSUE THREAD

**Issue by rcmaehl** [meetrevision/playbook#6]
RevisionOS removes various features that may be needed to free up system resources. An obvious side effect of this is that these features are lost and can't not be easily reinstalled.

A few options are available that can disable processes and services without stripping them out completely.

## NTSuspendProcess
NTSuspendProcess halts processing of the process or service but keeps the process resources in RAM so they can continue to be used once the process is resumed. This provides quick disabling and renabling of features without having to load the resources used back into RAM. The obvious downside to this is RAM usage is not decreased.

## Image File Execution Options
Image FIle Execution Options, along with it's filter option, allow calls to execute processes or services to be intercepted, and optionally ignored altogether. This can be applied and removed at any time in the Registry without needing a reboot or relog to disable processes or services.

Perhaps users can be given the option to customize what features they want "removed", "disabled", or "disabled in RAM" which will improve compatibility and security, while still heavily reducing resource usage.

**Comment by dreammjow** [comment]
We don't remove many components, here is the full list that we remove (copied from our NTLite's preset):

```
<c>asimov 'Telemetry Client'</c>
<c>assembly.net '.NET assembly cache'</c>
<c>ceip 'CEIP (SQM)'</c>
<c>errorreporting 'Windows Error Reporting'</c>
<c>firstlogonanim 'First-logon animation'</c>
<c>indeo 'Intel Indeo Codecs'</c>
<c>insiderhub 'Windows Insider Program'</c>
<c>lcu 'Cumulative Update cache (LCU)'</c>
<c>manifestbackup 'Manifest Backup (WinSxS\Backup)'</c>
<c>manualsetup 'Manual Setup'</c>
<c>Microsoft.549981C3F5F10 'Cortana'</c>
<c>Microsoft.Advertising.Xaml 'Microsoft Advertising SDK for XAML'</c>
<c>Microsoft.BingWeather 'MSN Weather'</c>
<c>Microsoft.GetHelp 'Get Help'</c>
<c>Microsoft.Getstarted 'Tips (Get Started)'</c>
<c>Microsoft.Microsoft3DViewer '3D Viewer'</c>
<c>Microsoft.MicrosoftEdge 'Microsoft Edge (Legacy)'</c>
<c>Microsoft.MicrosoftEdgeDevToolsClient 'Microsoft Edge DevTools Client'</c>
<c>Microsoft.MicrosoftOfficeHub 'Office'</c>
<c>Microsoft.MicrosoftSolitaireCollection 'Microsoft Solitaire Collection'</c>
<c>Microsoft.MicrosoftStickyNotes 'Microsoft Sticky Notes'</c>
<c>Microsoft.MixedReality.Portal 'Mixed Reality Portal'</c>
<c>Microsoft.MSPaint 'Paint 3D'</c>
<c>Microsoft.Office.OneNote 'OneNote'</c>
<c>Microsoft.People 'Microsoft People'</c>
<c>Microsoft.SkypeApp 'Skype'</c>
<c>Microsoft.Windows.PeopleExperienceHost 'Windows Shell Experience'</c>
<c>Microsoft.Windows.Photos 'Microsoft Photos'</c>
<c>Microsoft.Windows.SecureAssessmentBrowser 'Take a Test'</c>
<c>Microsoft.WindowsAlarms 'Windows Alarms &amp; Clock'</c>
<c>Microsoft.WindowsCamera 'Windows Camera'</c>
<c>microsoft.windowscommunicationsapps 'Mail and Calendar'</c>
<c>Microsoft.WindowsFeedbackHub 'Feedback Hub'</c>
<c>Microsoft.WindowsMaps 'Windows Maps'</c>
<c>Microsoft.WindowsSoundRecorder 'Windows Voice Recorder'</c>
<c>Microsoft.ZuneMusic 'Groove Music'</c>
<c>Microsoft.ZuneVideo 'Movies &amp; TV'</c>
<c>onedrive</c>
<c>photoviewer32 'Photo Viewer - 32 bit'</c>
<c>retaildemo 'Retail Demo Content'</c>
<c>screensavers</c>
<c>skypeortc 'Skype ORTC'</c>
<c>soundthemes 'Sound Themes'</c>
<c>sourcessxsdir 'Manual feature repository'</c>
<c>supportdir 'Support directory'</c>
<c>targetedcontent32 'Targeted Content Service - 32 bit'</c>
<c>tempcache 'Cache and temp files'</c>
<c>unp 'Universal Notification Platform (UNP)'</c>
<c>wallpapers 'Wallpapers (Themes)'</c>
<c>windowstogo 'Windows To Go'</c>

and Edge Chromium*
```

Bringing back `Windows Insider Program` isn't our priority, and removed UWP components can be reinstalled from MS Store.. If there are any other components you need, let me know and we might consider adding them with your suggestion.
