### ISSUE TITLE
[FEATURE]: Option to disable policies for Firefox

### ISSUE THREAD

**Issue by Stryxus** [meetrevision/playbook#60]
### Description

There are policies that I dont want in Firefox and I am sure many people dont even know what a Windows policy is so why are they forced on us? I also keep getting 2 ReviOS bookmarks forced upon me, they reappear on reopening Firefox.

I do web development and sometimes need settings changed which the policies enforce, which also apply to all Firefox channels too.

This requires an option and explanation when setting up.

### Benefit

Removal of annoying bookmarks as well as policies which could hinder the user experience based on use-case.

### Have you searched for similar feature requests?

- [X] I have searched for similar feature requests and found none.

**Comment by melo936** [comment]
The https://github.com/meetrevision/playbook/commit/5c9f8cef1bb8ed724bff450b96778f5b2ea9516c commit addresses the bookmark problem and the other policies shouldn't be harmful.
