### ISSUE TITLE
[BUG]: 无法打开设置里的系统

### ISSUE THREAD

**Issue by QAQQIAOY** [meetrevision/playbook#68]
### Describe the bug

我试图打开设置里的系统，对电源进行更改，单无法打开

### Steps to reproduce

1. 打开所有设置
2. 点击系统
3. 一闪而过它就关闭了系统设置界面
4. 
5. 
6. 

### Expected behavior

希望顺利打开设置里的系统，对电源显示等选项进行设置

### Environment

- OS Build Number & Edition: `type here`win10
- ReviOS Version: `type here`23.12
- Specs: `type here`

### Have you searched for similar issues?

- [X] I have searched for similar issues and found none.

**Comment by melo936** [comment]
Sorry, I do not speak Chinese. Please edit your comment and represent the issue in English.
