### ISSUE TITLE
[BUG]: The button start recording on Xbox toolbar is gray outed.

### ISSUE THREAD

**Issue by 0samuraiE** [meetrevision/playbook#74]
### Describe the bug

I was trying the procedure in revision faq.
But not fixed yet.

### Steps to reproduce

1.  apply playbook and open Xbox toolbar with WIN+G.

### Expected behavior

I expected I can record my screen using Xbox toolbar. 

### Environment

- OS Build Number & Edition:  Windows 11 23H2
- ReviOS Version: ReviOS Playbook 23.12
- Specs:  Device name	DESKTOP-TQRGGI0
Processor	13th Gen Intel(R) Core(TM) i7-13700K   3.40 GHz
Installed RAM	32.0 GB (31.7 GB usable)
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

### Have you searched for similar issues?

- [X] I have searched for similar issues and found none.

**Comment by melo936** [comment]
Open Terminal and enter the following commands:

```
reg add "HKCU\Software\Microsoft\Windows\CurrentVersion\GameDVR" /v "AppCaptureEnabled" /t REG_DWORD /d 1 /f
reg add "HKCU\System\GameConfigStore" /v "GameDVR_Enabled" /t REG_DWORD /d 1 /f
```

Once it's done, restart your PC.

**Comment by Stryxus** [comment]
It would be nice if there was an option to toggle Xbox DVR. Some of us use it, and it's especially helpful for HDR recording/screenshots.

**Comment by melo936** [comment]
> It would be nice if there was an option to toggle Xbox DVR. Some of us use it, and it's especially helpful for HDR recording/screenshots.

I think it would be more appropriate if it gets enabled it by default and provide a toggle in Revision Tool instead of the playbook
