### ISSUE TITLE
[BUG]: WSA won't Start

### ISSUE THREAD

**Issue by aboodgamer24** [meetrevision/playbook#79]
### Describe the bug

After installed WSA on win11, it didn't work, I tried enable Virtualization stuff options in BIOS and enable Hyper-V and Virtual machine platform in windows features same thing.
much thanks for fixing.

### Steps to reproduce

1. 
2. 
3. 
4. 

### Expected behavior

![image](https://github.com/meetrevision/playbook/assets/30497609/24a75333-c495-4eb1-a7d4-63009cb33bb0)
I think this causing the problem.

### Environment

- OS Build Number & Edition: `22631.286`
- ReviOS Version: `23.12`
- Specs: `R5 5600, 16GB Ram, RX 6750XT`

### Have you searched for similar issues?

- [X] I have searched for similar issues and found none.

**Comment by melo936** [comment]
Could you provide the steps for installing WSA? If you are using the Insider version, it might be the cause.

**Comment by aboodgamer24** [comment]
> Could you provide the steps for installing WSA? If you are using the Insider version, it might be the cause.

I will make full format soon for my RIG than I will try install WSA again.

**Comment by Stryxus** [comment]
> > Could you provide the steps for installing WSA? If you are using the Insider version, it might be the cause.
> 
> I will make full format soon for my RIG than I will try install WSA again.

I can confirm WSA works fine. It must be something to do with your system

**Comment by artemscine** [comment]
> > > Could you provide the steps for installing WSA? If you are using the Insider version, it might be the cause.
> > 
> > 
> > I will make full format soon for my RIG than I will try install WSA again.
> 
> I can confirm WSA works fine. It must be something to do with your system
I confirm that after installing playbook (23.12) on win10/11, wsa completely refuses to work.

**Comment by artemscine** [comment]
> I can confirm WSA works fine. It must be something to do with your system

I confirm that after installing playbook (23.12) on win10/11, wsa completely refuses to work.

**Comment by aboodgamer24** [comment]
> > I can confirm WSA works fine. It must be something to do with your system
> 
> I confirm that after installing playbook (23.12) on win10/11, wsa completely refuses to work. I have nstalled wsa before installing the playbook - everything works

That's exactly what happened to me

**Comment by aboodgamer24** [comment]
> > I can confirm WSA works fine. It must be something to do with your system
> 
> I confirm that after installing playbook (23.12) on win10/11, wsa completely refuses to work. I have nstalled wsa before installing the playbook - everything works

That's exactly what happened to me

**Comment by melo936** [comment]
> > I can confirm WSA works fine. It must be something to do with your system
> 
> I confirm that after installing playbook (23.12) on win10/11, wsa completely refuses to work. I have nstalled wsa before installing the playbook - everything works

Here's your text with corrected grammar:

I've installed the WSA Retail build (not Insider) on ReviOS 23.12, and it has worked perfectly fine. Could you provide any logs related to WSA from Event Viewer? Additionally, I would appreciate it if you could provide the steps for installing WSA.

**Comment by melo936** [comment]
Tested on Windows 11 Home 23H2 (22631.3155) MVS ISO February with Revision's Ventoy configuration - [More info](https://www.revi.cc/docs/playbook/installstock).

Playbook: https://github.com/meetrevision/playbook/commit/d75afa9353526b17fc1afbdff6fd563eca587c43 - [available on my repository](https://github.com/melo936/playbook/releases)

Installed WSA from Revision Tool with the following ID and ring:

ID: `9P3395VX91NR`
Ring: `Retail/Stable`

I've used the following script to enable Hyper-V on Home: https://gist.github.com/HimDek/6edde284203a620745fad3f762be603b#enable-hyper-v

I also enabled `Virtual Machine Platform` and `Windows Hypervisor Platform` via Windows Features.

After restarting, I opened WSA and there was an error on the first run of Files, but the app still works fine:
![error](https://github.com/meetrevision/playbook/assets/50238852/35517785-e987-43c3-93f6-bc00a904f8d2)

Then I installed my own app (written in Flutter) via `adb`:
![Untitled](https://github.com/meetrevision/playbook/assets/50238852/066eb22c-5e53-448c-a9fa-45ff956b35d9)

**Comment by VolanDeVovan** [comment]
> Tested on Windows 11 Home 23H2 (22631.3155) MVS ISO February with Revision's Ventoy configuration - [More info](https://www.revi.cc/docs/playbook/installstock).
> 
> Playbook: [d75afa9](https://github.com/meetrevision/playbook/commit/d75afa9353526b17fc1afbdff6fd563eca587c43) - [available on my repository](https://github.com/melo936/playbook/releases)
> 
> Installed WSA from Revision Tool with the following ID and ring:
> 
> ID: `9P3395VX91NR` Ring: `Retail/Stable`
> 
> I've used the following script to enable Hyper-V on Home: https://gist.github.com/HimDek/6edde284203a620745fad3f762be603b#enable-hyper-v
> 
> I also enabled `Virtual Machine Platform` and `Windows Hypervisor Platform` via Windows Features.
> 
> After restarting, I opened WSA and there was an error on the first run of Files, but the app still works fine: ![error](https://private-user-images.githubusercontent.com/50238852/306971725-35517785-e987-43c3-93f6-bc00a904f8d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxNjQ4NjQsIm5iZiI6MTcwOTE2NDU2NCwicGF0aCI6Ii81MDIzODg1Mi8zMDY5NzE3MjUtMzU1MTc3ODUtZTk4Ny00M2MzLTkzZjYtYmMwMGE5MDRmOGQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDIzNTYwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkMDc4ZGIzYjE3NzIyYjQ4MzZmZGZiNzU4YmI0NDkzOWRmODYyMDRhZDgyNzJlNTU1NjkzZjIxN2MxMzQyMDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gzMdOShnmXIzg3QIDihiIVh4daocqM8tgQFCoaFzPBw)
> 
> Then I installed my own app (written in Flutter) via `adb`: ![Untitled](https://private-user-images.githubusercontent.com/50238852/306972047-066eb22c-5e53-448c-a9fa-45ff956b35d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxNjQ4NjQsIm5iZiI6MTcwOTE2NDU2NCwicGF0aCI6Ii81MDIzODg1Mi8zMDY5NzIwNDctMDY2ZWIyMmMtNWU1My00NDhjLWE5ZmEtNDVmZjk1NmIzNWQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDIzNTYwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwMTBhYmM1ZjY2MGJkNTJkYjI1Y2RlNjQ5YmYwNjQ5MDdhMmEwYWU1ZjMxZjA1MWU3MjM2Y2ZhNmNjZGZiMmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.c1yCnlYTH5n0b__jV1dMU5tE6nnpYrVD0MCbiEsuEpQ)

Your fork fixed everything for me.
