### ISSUE TITLE
bug: integer scaling not working in AMD Software Adrenalin edition on Lenovo Legion Go

### ISSUE THREAD

**Issue by JustinSuss** [meetrevision/playbook#86]
### Describe the bug

Installed fresh Windows 11 pro, installed drivers, tried Integer Scaling, it works. Reinstalled windows (for a clean install), applied ReviOS playbook, installed drivers/DirectX/Visual C++, Integer Scaling stopped working

### Steps to reproduce

1. Install Windows 11 Pro
2. Apply ReviOS playbook
3. Install drivers/DirectX/Visual C++
4. Right-click on desktop
5. Click "Amd Software"
6. Navigate to "Games"
7. Navigate to "Display"
8. Turn on GPU Scaling
9. Turn on Integer Scaling
10. Set the resolution of LeGo to 1920x1200 (Screen should show big black borders, but it doesn't)
11. Issue reproduced

### Expected behavior

On step 10, picture should get smaller and borders should become larger, which is not happening

### Environment

- OS Build Number & Edition: `Windows 11 Pro 23H2, build 22631.3155`
- ReviOS Version: `ReviOS 11 23.12`
- Specs: 2023/11/03 Lenovo Legion Go `CPU: AMD Ryzen Z1 Extreme; GPU: AMD APU (similar to Radeon 780M) with 6GB of VRAM; RAM: 16GB (6 is dedicated to VRAM so 10) with 7500 MT/s`

### Additional information

Tried to reinstall dirvers and AMD Software, tried turning Fullscreen and Windowed optimizations both ON and OFF.

### Have you searched for similar issues?

- [X] I have searched for similar issues and found none.

**Comment by melo936** [comment]
Could you try to apply this [playbook](https://github.com/melo936/playbook/releases/tag/24.03.02) on a fresh install?


If it still doesn't work, please open PowerShell/Terminal as Administrator and enter the following command, restart and see if it works:
`Get-WindowsPackage -online -PackageName *ReviOS* | Remove-WindowsPackage -Online`

**Comment by melo936** [comment]
> Many thanks, the issue was solved, integer scaling now works!

That's good to hear that we are on the correct road, but the actual problem hasn't been solved yet. One of the system components that we removed causes the issue.
