### ISSUE TITLE
[FEATURE]: New 2024 upgrade patch and offline iso image files

### ISSUE THREAD

**Issue by petercao** [meetrevision/playbook#90]
### Description

Hi guys,
  for a long time I just us revios from you guy, and which is very stable and fast, I use this os solve lots of problem of my job;
but for such a long time , more than 3 month, I didn't see any upgrade patch from your site,

Hope you can release new patch soon.
and meanwhile, I hope you can still release us the offline iso file, because someone may didn't restore your iso fle yet.

### Benefit

improve system performance anf functionality

### Have you searched for similar feature requests?

- [X] I have searched for similar feature requests and found none.

**Comment by petercao** [comment]
Is anyone here can give me a  reply?

**Comment by StasiumDev** [comment]
We no longer provide modified ISOs and will not do so in the future for two reasons:

- It is illegal.
- They require significant time to maintain.

An update for the Playbook is currently in progress. Please be patient.

**Comment by gitchuon** [comment]
> An update for the Playbook is currently in progress. Please be patient.

Can you tell me when? I plan to reinstall Windows and use ReviOS when the new version is released.

**Comment by StasiumDev** [comment]
> > An update for the Playbook is currently in progress. Please be patient.
> 
> Can you tell me when? I plan to reinstall Windows and use ReviOS when the new version is released.

There is no ETA as of right now

**Comment by Dillensad** [comment]
Hi there,

I just wanted to chime in and express how much I appreciate this project. It has been incredibly useful to me and I am excited to see it continue to develop. In particular, I have been keeping an eye on this issue and am eagerly awaiting the next release with this fix included. Thank you so much for all of your hard work and keep up the great job!

**Comment by Dillensad** [comment]
> Hi there,
> 
> I just wanted to chime in and express how much I appreciate this project. It has been incredibly useful to me and I am excited to see it continue to develop. In particular, I have been keeping an eye on this issue and am eagerly awaiting the next release with this fix included. Thank you so much for all of your hard work and keep up the great job!

I am a student from China who extremely rely on your good changes on windows when I am using my laptop to finish my work. And many friends of me like revios too!

**Comment by ThePhaseless** [comment]
@Dillensad You can close this issue now 😉
