### ISSUE TITLE
[BUG]: home office banner is back

### ISSUE THREAD

**Issue by Lyceris-chan** [meetrevision/playbook#98]
### Describe the bug

open settings after running a playbook based on https://github.com/meetrevision/playbook/commit/176cbaf5c65fd91aa700f5aae886280fd9fbee7c and see the banner

![image](https://github.com/meetrevision/playbook/assets/52329982/f82c37e2-9bbb-4b5c-9cc0-c655cccf77ff)

### Steps to reproduce

1. open settings 
2. observe banner
3. 
4. 

### Expected behavior

the banner shouldn't be there as https://github.com/meetrevision/playbook/commit/3224947e4a62482cb4ef7adf0ee0b4bb4ff6e2fb should've fixed it

### Environment

- OS Build Number & Edition: `22631.3447 - Windows 11 pro`
- ReviOS Version: `build against the commit mentioned earlier`
- Specs:  `Ryzen 5 5600x 32gb ram rx6800 msi b550m pro vdh wifi `

### Have you searched for similar issues?

- [X] I have searched for similar issues and found none.

**Comment by melo936** [comment]
The only solution would be to completely hide the page
